name = "Muxel"
version = "1.1.1"
description = "A simple, lightweight & customizable, one-page, HUGO portfolio theme."
homepage = "https://github.com/logstacklabs/muxel.git"
license = "CC BY-NC-SA 4.0"
licenselink = "https://github.com/logstacklabs/muxel/blob/main/docs/LICENSE"
tags = [
    "portfolio",
    "personal",
    "clean",
    "onepage",
    "about me",
    "professional"
]
features = [
    "Responsive",
    "Lightweight",
    "Single Page Layout",
    "Font Awesome Support",
    "Goat Analytics Support",
    "Google Analytics Support"
]

min_version = "0.148.0"

[[authors]]
    name = "Muhammed A."
    homepage = "https://msio.me"

[[authors]]
    name = "LOGSTACK LABS"
    homepage = "https://logstack.dev"
